import { EditorElement } from "../store/useEditorStore";

export const DEFAULTS: Record<string, Partial<EditorElement>> = {
  heading: {
    type: 'text',
    w: 500,
    h: 56,
    text: 'Your Name',
    fontSize: 40,
    fontWeight: '700',
    fontFamily: 'Playfair Display',
    color: '#1a1a1a',
    textAlign: 'left',
    italic: false,
    underline: false,
    lineHeight: 1.2,
    letterSpacing: 0,
    rotation: 0,
  },
  subheading: {
    type: 'text',
    w: 400,
    h: 30,
    text: 'Job Title',
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Plus Jakarta Sans',
    color: '#666666',
    textAlign: 'left',
    italic: false,
    underline: false,
    lineHeight: 1.4,
    letterSpacing: 2,
    rotation: 0,
  },
  body: {
    type: 'text',
    w: 500,
    h: 80,
    text: 'Write your professional summary here. Click to edit this text block.',
    fontSize: 13,
    fontWeight: '400',
    fontFamily: 'Plus Jakarta Sans',
    color: '#444444',
    textAlign: 'left',
    italic: false,
    underline: false,
    lineHeight: 1.75,
    letterSpacing: 0,
    rotation: 0,
  },
  label: {
    type: 'text',
    w: 200,
    h: 18,
    text: 'SECTION LABEL',
    fontSize: 10,
    fontWeight: '700',
    fontFamily: 'Plus Jakarta Sans',
    color: '#999999',
    textAlign: 'left',
    italic: false,
    underline: false,
    lineHeight: 1.4,
    letterSpacing: 3,
    rotation: 0,
  },
  rect: {
    type: 'shape',
    shape: 'rect',
    w: 200,
    h: 80,
    fill: '#D6A85F',
    stroke: 'none',
    strokeWidth: 0,
    radius: 0,
    opacity: 1,
    rotation: 0,
  },
  circle: {
    type: 'shape',
    shape: 'circle',
    w: 80,
    h: 80,
    fill: '#D6A85F',
    stroke: 'none',
    strokeWidth: 0,
    radius: 50,
    opacity: 1,
    rotation: 0,
  },
  triangle: {
    type: 'shape',
    shape: 'triangle',
    w: 80,
    h: 70,
    fill: '#D6A85F',
    stroke: 'none',
    strokeWidth: 0,
    radius: 0,
    opacity: 1,
    rotation: 0,
  },
  hexagon: {
    type: 'shape',
    shape: 'hexagon',
    w: 80,
    h: 80,
    fill: '#D6A85F',
    stroke: 'none',
    strokeWidth: 0,
    radius: 0,
    opacity: 1,
    rotation: 0,
  },
  star: {
    type: 'shape',
    shape: 'star',
    w: 80,
    h: 80,
    fill: '#D6A85F',
    stroke: 'none',
    strokeWidth: 0,
    radius: 0,
    opacity: 1,
    rotation: 0,
  },
  heart: {
    type: 'shape',
    shape: 'heart',
    w: 80,
    h: 80,
    fill: '#D6A85F',
    stroke: 'none',
    strokeWidth: 0,
    radius: 0,
    opacity: 1,
    rotation: 0,
  },
  octagon: {
    type: 'shape',
    shape: 'octagon',
    w: 80,
    h: 80,
    fill: '#D6A85F',
    stroke: 'none',
    strokeWidth: 0,
    radius: 0,
    opacity: 1,
    rotation: 0,
  },
  pentagon: {
    type: 'shape',
    shape: 'pentagon',
    w: 80,
    h: 80,
    fill: '#D6A85F',
    stroke: 'none',
    strokeWidth: 0,
    radius: 0,
    opacity: 1,
    rotation: 0,
  },
  'arrow-right': {
    type: 'shape',
    shape: 'arrow-right',
    w: 80,
    h: 40,
    fill: '#D6A85F',
    stroke: 'none',
    strokeWidth: 0,
    radius: 0,
    opacity: 1,
    rotation: 0,
  },
  divider: {
    type: 'divider',
    w: 600,
    h: 12,
    color: '#DDDDDD',
    thickness: 1,
    style: 'solid',
    rotation: 0,
  },
  photo: {
    type: 'image',
    w: 120,
    h: 150,
    src: null,
    radius: 0,
    rotation: 0,
  },
  skillbar: {
    type: 'skillbar',
    w: 280,
    h: 32,
    label: 'Design',
    value: 80,
    color: '#D6A85F',
    bg: '#EEEEEE',
    fontSize: 12,
    fontFamily: 'Plus Jakarta Sans',
    textColor: '#333',
    rotation: 0,
  },
  badge: {
    type: 'shape',
    shape: 'badge',
    w: 110,
    h: 30,
    fill: 'rgba(214,168,95,0.1)',
    stroke: 'rgba(214,168,95,0.4)',
    strokeWidth: 1,
    radius: 15,
    opacity: 1,
    text: 'Skill Name',
    textColor: '#D6A85F',
    fontSize: 11,
    fontFamily: 'Plus Jakarta Sans',
    rotation: 0,
  },
};
